Repository fcakyon/yolov5-pip, pull requests merged in 2022-09, with the labels that each got.

#139 fix evolve
  .github/workflows/ci.yml
  .github/workflows/package_testing.yml
  yolov5/train.py
Labels: bug, enhancement

#141 Fix pypi package version not updating in readme
  README.md
Labels: documentation, enhancement

#147 add classify and segment usage into readme
  README.md
Labels: documentation

#151 revert dataset path resolve
  yolov5/utils/general.py
Labels: enhancement
